const teamLogos: Record<string, string> = {
  "Luton Town": "/teamlogo/Luton Town.png",
  "Middlesbrough": "/teamlogo/Middlesborough.png",
  "Barnsley": "/teamlogo/Barnsley.png",
  "Fulham": "/teamlogo/Fullham.png",
  "Blackburn Rovers": "/teamlogo/Blackburn Rovers.png",
  "Charlton": "/teamlogo/Charlton.png",
  "Brentford": "/teamlogo/Brentford.png",
  "Birmingham City": "/teamlogo/Birmingham City",
  "Millwall": "/teamlogo/Milwall.png",
  "Preston North End": "/teamlogo/Preston North End FC.png",
  "Reading": "/teamlogo/Reading.png",
  "Sheffield Weds": "/teamlogo/Sheffield Wednesday.png",
  "Stoke City": "/teamlogo/Stoke City.png",
  "Queens Park Rangers": "/teamlogo/QPR.png",
  "Swansea City": "/teamlogo/Swansea.png",
  "Hull City": "/teamlogo/Hull City.png",
  "Wigan Athletic": "/teamlogo/Wigan Athletic.png",
  "Cardiff City": "/teamlogo/Cardiff City.png",
  "Nottingham Forest": "/teamlogo/Nottingham Forest.png",
  "West Bromwich Albion": "/teamlogo/West Brom Albion.png",
  "Bristol City": "/teamlogo/Bristol.png",
  "Leeds United": "/teamlogo/Leeds.png",
  "Huddersfield Town": "/teamlogo/Huddersfield Town.png",
  "Derby County": "/teamlogo/Derby County.png",
  "Liverpool": "/teamlogo/Liverpool.png",
  "Norwich City": "/teamlogo/Norwich.png",
  "West Ham United": "/teamlogo/West Ham.png",
  "Manchester City": "/teamlogo/Manchester City.png",
  "Bournemouth": "/teamlogo/Bournemoth.png",
  "Sheffield United": "/teamlogo/Sheffield.png",
  "Burnley": "/teamlogo/Burnley.png",
  "Southampton": "/teamlogo/Southampton.png",
  "Crystal Palace": "/teamlogo/Crystal Palace.png",
  "Everton": "/teamlogo/Everton.png",
  "Watford": "/teamlogo/Watford.png",
  "Brighton & Hove Albion": "/teamlogo/Brighton.png",
  "Tottenham Hotspur": "/teamlogo/Tottenham.png",
  "Aston Villa": "/teamlogo/Aston Villa.png",
  "Leicester City": "/teamlogo/Leicester.png",
  "Wolverhampton Wanderers": "/teamlogo/Wolves.png",
  "Newcastle United": "/teamlogo/Newcastle.png",
  "Arsenal": "/teamlogo/Arsenal.png",
  "Manchester United": "/teamlogo/Manchester United.png",
  "Chelsea": "/teamlogo/Chelsea.png",
  "Wycombe": "/teamlogo/Wycombe.png",
  "Rotherham": "/teamlogo/Rotherham.png",
  "Coventry City": "/teamlogo/Coventry.png",
  "Blackpool": "/teamlogo/Blackpool.png",
  "Peterboro": "/teamlogo/Peterboro.png",
  "Sunderland": "/teamlogo/Sunderland.png",
  "Plymouth": "/teamlogo/Plymouth Argyle.png",
  "Ipswich": "/teamlogo/Ipswich.png",
  "Dunfermline Athletic": "/teamlogo/Dunfermline Athletic.png",
  "Dundee": "/teamlogo/Dundee FC.png",
  "Alloa": "/teamlogo/Alloa.png",
  "Partick Thistle": "/teamlogo/Partick Thistle.png",
  "Arbroath": "/teamlogo/Arbroath.png",
  "Queen of Sth": "/teamlogo/Queen of Sth.png",
  "Ayr": "/teamlogo/Ayr.png",
  "Morton": "/teamlogo/Greenock Morton.png",
  "Dundee United": "/teamlogo/Dundee United.png",
  "Inverness C": "/teamlogo/Inverness C.png",
  "Celtic": "/teamlogo/Celtic.png",
  "St Johnstone": "/teamlogo/St. Johnstone.png",
  "Hibernian": "/teamlogo/Hibernian.png",
  "St Mirren": "/teamlogo/St. Mirren.png",
  "Livingston": "/teamlogo/Livingston.png",
  "Motherwell": "/teamlogo/Motherwell.png",
  "Ross County": "/teamlogo/Ross County.png",
  "Hamilton": "/teamlogo/Hamilton.png",
  "Kilmarnock": "/teamlogo/Kilmarnock F.C..png",
  "Rangers": "/teamlogo/Rangers.png",
  "Aberdeen": "/teamlogo/Aberdeen.png",
  "Hearts": "/teamlogo/Hearts.png",
  "Raith Rvs": "/teamlogo/Raith Rovers.png",
  "Cove Rangers": "/teamlogo/Cove Rangers.png",
  "Queen's Park": "/teamlogo/Queens Park .png",
  "Airdrie Utd": "/teamlogo/Airdrieonians.png",
  "Raith Rovers": "/teamlogo/Raith Rovers.png",
  "Airdrieonians": "/teamlogo/Airdrieonians.png",
  "Sheffield Wednesday": "/teamlogo/Sheffield Wednesday.png",
  "Portsmouth": "/teamlogo/Portsmouth.png",
  "Oxford Utd": "/teamlogo/Oxford United.png",
  "Falkirk": "/teamlogo/Falkirk.png",
  "St. Mirren": "/teamlogo/St. Mirren.png",
  "England": "/teamlogo/England.png",
  "Scotland": "/teamlogo/Scotland.png"
};

export default teamLogos;
