const teamLogos: Record<string, string> = {
  "Luton Town": "/teamlogo/Luton Town.png",
  "Middlesbrough": "/teamlogo/Middlesborough.png",
  "Barnsley": "/teamlogo/Barnsley.png",
  "Fulham": "/teamlogo/Fullham.png",
  "Blackburn Rovers": "/teamlogo/Blackburn Rovers.png",
  "Charlton": "/teamlogo/Charlton.png",
  "Brentford": "/teamlogo/Brentford.png",
  "Birmingham City": "/teamlogo/Birmingham City",
  "Millwall": "/teamlogo/Milwall.png",
  "Preston North End": "/teamlogo/Preston North End FC.png",
  "Reading": "/teamlogo/Reading.png",
  "Sheffield Weds": "/teamlogo/Sheffield Wednesday.png",
  "Stoke City": "/teamlogo/Stoke City.png",
  "Queens Park Rangers": "/teamlogo/QPR.png",
  "Swansea City": "/teamlogo/Swansea.png",
  "Hull City": "/teamlogo/Hull City.png",
  "Wigan Athletic": "/teamlogo/Wigan Athletic.png",
  "Cardiff City": "/teamlogo/Cardiff City.png",
  "Nottingham Forest": "/teamlogo/Nottingham Forest.png",
  "West Bromwich Albion": "/teamlogo/West Brom Albion.png",
  "Bristol City": "/teamlogo/Bristol.png",
  "Leeds United": "/teamlogo/Leeds.png",
  "Huddersfield Town": "/teamlogo/Huddersfield Town.png",
  "Derby County": "/teamlogo/Derby County.png",
  "Liverpool": "/teamlogo/Liverpool.png",
  "Norwich City": "/teamlogo/Norwich.png",
  "West Ham United": "/teamlogo/West Ham.png",
  "Manchester City": "/teamlogo/Manchester City.png",
  "Bournemouth": "/teamlogo/Bournemoth.png",
  "Sheffield United": "/teamlogo/Sheffield.png",
  "Burnley": "/teamlogo/Burnley.png",
  "Southampton": "/teamlogo/Southampton.png",
  "Crystal Palace": "/teamlogo/Crystal Palace.png",
  "Everton": "/teamlogo/Everton.png",
  "Watford": "/teamlogo/Watford.png",
  "Brighton & Hove Albion": "/teamlogo/Brighton.png",
  "Tottenham Hotspur": "/teamlogo/Tottenham.png",
  "Aston Villa": "/teamlogo/Aston Villa.png",
  "Leicester City": "/teamlogo/Leicester.png",
  "Wolverhampton Wanderers": "/teamlogo/Wolves.png",
  "Newcastle United": "/teamlogo/Newcastle.png",
  "Arsenal": "/teamlogo/Arsenal.png",
  "Manchester United": "/teamlogo/Manchester United.png",
  "Chelsea": "/teamlogo/Chelsea.png",
  "Wycombe": "/teamlogo/Wycombe.png",
  "Rotherham": "/teamlogo/Rotherham.png",
  "Coventry City": "/teamlogo/Coventry.png",
  "Blackpool": "/teamlogo/Blackpool.png",
  "Peterboro": "/teamlogo/Peterboro.png",
  "Sunderland": "/teamlogo/Sunderland.png",
  "Plymouth": "/teamlogo/Plymouth Argyle.png",
  "Ipswich": "/teamlogo/Ipswich.png",
  "Dunfermline Athletic": "/teamlogo/Dunfermline Athletic.png",
  "Dundee": "/teamlogo/Dundee FC.png",
  "Alloa": "/teamlogo/Alloa.png",
  "Partick Thistle": "/teamlogo/Partick Thistle.png",
  "Arbroath": "/teamlogo/Arbroath.png",
  "Queen of Sth": "/teamlogo/Queen of Sth.png",
  "Ayr": "/teamlogo/Ayr.png",
  "Morton": "/teamlogo/Greenock Morton.png",
  "Dundee United": "/teamlogo/Dundee United.png",
  "Inverness C": "/teamlogo/Inverness C.png",
  "Celtic": "/teamlogo/Celtic.png",
  "St. Johnstone": "/teamlogo/St. Johnstone.png",
  "Hibernian": "/teamlogo/Hibernian.png",
  "St Mirren": "/teamlogo/St. Mirren.png",
  "Livingston": "/teamlogo/Livingston.png",
  "Motherwell": "/teamlogo/Motherwell.png",
  "Ross County": "/teamlogo/Ross County.png",
  "Hamilton": "/teamlogo/Hamilton.png",
  "Kilmarnock": "/teamlogo/Kilmarnock F.C..png",
  "Rangers": "/teamlogo/Rangers.png",
  "Aberdeen": "/teamlogo/Aberdeen.png",
  "Hearts": "/teamlogo/Hearts.png",
  "Raith Rvs": "/teamlogo/Raith Rovers.png",
  "Cove Rangers": "/teamlogo/Cove Rangers.png",
  "Queen's Park": "/teamlogo/Queens Park .png",
  "Airdrie Utd": "/teamlogo/Airdrieonians.png",
  "Raith Rovers": "/teamlogo/Raith Rovers.png",
  "Airdrieonians": "/teamlogo/Airdrieonians.png",
  "Sheffield Wednesday": "/teamlogo/Sheffield Wednesday.png",
  "Portsmouth": "/teamlogo/Portsmouth.png",
  "Oxford Utd": "/teamlogo/Oxford United.png",
  "Falkirk": "/teamlogo/Falkirk.png",
  "St. Mirren": "/teamlogo/St. Mirren.png",
  "England": "/teamlogo/England.png",
  "Scotland": "/teamlogo/Scotland.png",
  "Turkey": "/teamlogo/Turkey.png",
  "Italy": "/teamlogo/Italy.png",
  "German": "/teamlogo/German.png",
  "Spain": "/teamlogo/Spain.png",

  
  "Süper Lig": "/teamlogo/Super Lig.png",
  "Serie A": "/teamlogo/Serie A.png",
  "Serie B": "/teamlogo/Serie B.png",
  "La Liga": "/teamlogo/La Liga.png",
  "La Liga 2": "/teamlogo/La Liga2.png",
  "Bundesliga": "/teamlogo/Bundesliga.png",
  "Bundesliga 2": "/teamlogo/Bundesliga 2.png",


  "Istanbulspor": "",
  "Trabzonspor": "/teamlogo/Trabzonspor.png",
  "Sivasspor": "/teamlogo/Sivasspor.png",
  "Gaziantep FK": "/teamlogo/Gaziantep.png",
  "Besiktas": "/teamlogo/Besiktas.png",
  "Kayserispor": "/teamlogo/Kayserispor.png",
  "Giresunspor": "",
  "Adana Demirspor": "/teamlogo/Adana Demirspor.png",
  "Karagumruk": "",
  "Alanyaspor": "/teamlogo/Alanyaspor.png",
  "Antalyaspor": "/teamlogo/Antalyaspor.png",
  "Galatasaray": "/teamlogo/Galatasaray.png",
  "Buyuksehir Belediye Erzurumspor": "",
  "Kasimpasa": "/teamlogo/Kasimpasa.png",
  "Ankaragucu": "",
  "Konyaspor": "/teamlogo/Konyaspor.png",
  "Fenerbahce": "/teamlogo/Fenerbahce .png",
  "Umraniyespor": "",
  "Hatayspor": "/teamlogo/Hatayspor.png",
  "Caykur Rizespor": "/teamlogo/Rizespor.png",
  "Altay": "",
  "Goztep": "/teamlogo/Goztepe.png",
  "Yeni Malatyaspor": "",
  "Denizlispor": "",
  "Erzurum BB": "",
  "Genclerbirligi": "",
  "Pendikspor": "",
  "Samsunspor": "/teamlogo/Samsunspor.png",
  "Empoli": "/teamlogo/Empoli.png",
  "Verona": "/teamlogo/Verona.png",
  "Frosinone": "/teamlogo/Frosinone.png",
  "Napoli": "/teamlogo/Napoli.png",
  "Genoa": "/teamlogo/Genoa.png",
  "Fiorentina": "/teamlogo/Fiorentina.png",
  "Inter": "/teamlogo/Inter.png",
  "Monza": "/teamlogo/Monza.png",
  "Roma": "/teamlogo/Roma.png",
  "Salernitana": "/teamlogo/Salernitana.png",
  "Sassuolo": "/teamlogo/Sassuolo.png",
  "Atalanta": "/teamlogo/Atalanta.png",
  "Lecce": "/teamlogo/Lecce.png",
  "Lazio": "/teamlogo/Lazio.png",
  "Udinese": "/teamlogo/Udinese.png",
  "Juventus": "/teamlogo/Juventus.png",
  "Torino": "/teamlogo/Torino.png",
  "Cagliari": "/teamlogo/Cagliari.png",
  "Bologna": "/teamlogo/Bologna.png",
  "AC Milan": "/teamlogo/AC Milan.png",
  "Sampdoria": "/teamlogo/Sampdoria.png",
  "Cremonese": "/teamlogo/Cremonese.png",
  "Spezia": "/teamlogo/Spezia.png",
  "Venezia": "/teamlogo/Venezia.png",
  "Parma": "/teamlogo/Parma.png",
  "Crotone": "",
  "Benevento": "",
  "Brescia": "/teamlogo/Brescia.png",
  "Spal": "",
  "Bari": "/teamlogo/Bari.png",
  "Cittadella": "/teamlogo/Cittadella.png",
  "Pisa": "/teamlogo/Pisa.png",
  "Como": "/teamlogo/Como.png",
  "Palermo": "/teamlogo/Palermo.png",
  "Perugia": "",
  "Ascoli": "",
  "Ternana": "",
  "Cosenza": "/teamlogo/Cosenza.png",
  "Sudtirol": "/teamlogo/Sudtirol.png",
  "Modena": "/teamlogo/Modena.png",
  "Reggina": "/teamlogo/Reggiana.png",
  "Pordenone": "",
  "Vicenza": "",
  "Alessandria": "",
  "Virtus Entella": "",
  "Pescara": "",
  "Chievo": "",
  "Trapani": "",
  "Livorno": "",
  "Juve Stabia": "/teamlogo/Juve Stabia.png",
  "Catanzaro": "/teamlogo/US Catanzaro.png",
  "FeralpiSalo": "",
  "Lecco": "",
  "Osasuna": "/teamlogo/Osasuna.png",
  "Sevilla": "/teamlogo/Sevilla.png",
  "Celta": "/teamlogo/Celta Vigo.png",
  "Espanol": "/teamlogo/Espanyol.png",
  "Valladolid": "/teamlogo/Valladolid.png",
  "Villarreal": "/teamlogo/Villarreal.png",
  "Barcelona": "/teamlogo/Barcelona.png",
  "Vallecano": "/teamlogo/Rayo Vallecano.png",
  "Cadiz": "/teamlogo/Cadiz.png",
  "Real Sociedad": "/teamlogo/Real Sociedad.png",
  "Valencia": "/teamlogo/Valencia.png",
  "Girona": "/teamlogo/Girona.png",
  "Almeria": "/teamlogo/Almeria.png",
  "Real Madrid": "/teamlogo/Real Madrid.png",
  "Ath Bilbao": "/teamlogo/Athletic Club.png",
  "Mallorca": "/teamlogo/Mallorca.png",
  "Getafe": "/teamlogo/Getafe.png",
  "Ath Madrid": "/teamlogo/Atletico Madrid.png",
  "Betis": "/teamlogo/Real Betis.png",
  "Elche": "/teamlogo/Elche.png",
  "Levante": "/teamlogo/Levante.png",
  "Alaves": "/teamlogo/Alaves.png",
  "Granada": "/teamlogo/Granada.png",
  "Eibar": "/teamlogo/Eibar.png",
  "Huesca": "/teamlogo/Huesca.png",
  "Leganes": "/teamlogo/Leganes.png",
  "Las Palmas": "/teamlogo/Las Palmas.png",
  "Tenerife": "/teamlogo/Tenerife.png",
  "Mirandes": "/teamlogo/Mirandes .png",
  "Sp Gijon": "/teamlogo/Sporting Gijon.png",
  "Zaragoza": "/teamlogo/Real Zaragoza.png",
  "Santander": "/teamlogo/Racing.png",
  "Ibiza": "",
  "Burgos": "/teamlogo/Burgos.png",
  "Malaga": "/teamlogo/Malaga.png",
  "Oviedo": "/teamlogo/Oviedo.png",
  "Andorra": "",
  "Lugo": "",
  "Albacete": "/teamlogo/Albacete.png",
  "Cartagena": "/teamlogo/FC Cartagena.png",
  "Ponferradina": "",
  "Sociedad B": "",
  "Amorebieta": "",
  "Alcorcon": "",
  "Fuenlabrada": "",
  "CD Castellon": "/teamlogo/Castellon.png",
  "Logrones": "",
  "Sabadell": "",
  "Extremadura UD": "",
  "La Coruna": "/teamlogo/Deportivo.png",
  "Numancia": "",
  "Ferrol": "/teamlogo/Racing Ferrol.png",
  "Eldense": "/teamlogo/Eldense.png",
  "Ein Frankfurt": "/teamlogo/Eintracht Frankfurt.png",
  "Bayern Munich": "/teamlogo/Bayern.png",
  "Augsburg": "/teamlogo/Augsburg.png",
  "Freiburg": "/teamlogo/SC Freiburg.png",
  "Bochum": "/teamlogo/VfL Bochum.png",
  "Mainz": "/teamlogo/Mainz.png",
  "M'gladbach": "/teamlogo/Borussia Monchengladbach.png",
  "Hoffenheim": "/teamlogo/Hoffenheim.png",
  "Union Berlin": "/teamlogo/Union Berlin.png",
  "Hertha": "/teamlogo/Hertha.png",
  "Wolfsburg": "/teamlogo/Wolfsburg.png",
  "Werder Bremen": "/teamlogo/Werder.png",
  "Dortmund": "/teamlogo/Dortmund.png",
  "Leverkusen": "/teamlogo/Leverkusen.png",
  "Stuttgart": "/teamlogo/VfB Stuttgart.png",
  "RB Leipzig": "/teamlogo/RB Leipzig.png",
  "FC Koln": "/teamlogo/Koln.png",
  "Schalke 04": "/teamlogo/Schalke.png",
  "Bielefeld": "",
  "Greuther Furth": "/teamlogo/Furth.png",
  "Paderborn": "/teamlogo/Paderborn.png",
  "Fortuna Dusseldorf": "/teamlogo/Dusseldorf.png",
  "Heidenheim": "/teamlogo/Heidenheim.png",
  "Darmstadt": "/teamlogo/Darmstadt.png",
  "Kaiserslautern": "/teamlogo/1. FCK.png",
  "Hannover": "/teamlogo/Hannover 96.png",
  "Holstein Kiel": "/teamlogo/Holstein Kiel.png",
  "Regensburg": "/teamlogo/SSV Jahn Regensburg.png",
  "Sandhausen": "",
  "St. Pauli": "/teamlogo/FC St. Pauli.png",
  "Nurnberg": "/teamlogo/Nurnberg.png",
  "Magdeburg": "/teamlogo/FC Magdeburg.png",
  "Braunschweig": "/teamlogo/Eintracht Braunschweig.png",
  "Hamburg": "/teamlogo/Hamburger SV.png",
  "Hansa Rostock": "",
  "Karlsruhe": "/teamlogo/Karlsruher.png",
  "Dresden": "",
  "Ingolstadt": "",
  "Erzgebirge Aue": "",
  "Wurzburger Kickers": "",
  "Osnabruck": "",
  "Wehen": "",
  "Elversberg": "/teamlogo/SV Elversberg.png",
  "Hertha Berlin": "/teamlogo/Hertha.png",
  "Schalke": "/teamlogo/Schalke.png",
  "Atletico Madrid": "/teamlogo/Atletico Madrid.png",
  "Real Mallorca": "/teamlogo/Mallorca.png",
  "Espanyol": "/teamlogo/Espanyol.png",
  "Rayo Vallecano": "/teamlogo/Rayo Vallecano.png",
  "Entella": "",
  "Racing Santander": "/teamlogo/Racing.png",
  "Deportivo La Coruna": "/teamlogo/Deportivo.png",
  "Eyupspor": "/teamlogo/Eyupspor.png",
  "Goztepe": "/teamlogo/Goztepe.png",
  "Bodrum FK": "/teamlogo/Bodrum.png",
  "Cesena": "/teamlogo/Cesena.png",
  "Carrarese": "/teamlogo/Carrarese.png",
  "Mantova": "/teamlogo/Mantova.png",
  "Cordoba": "/teamlogo/Cordoba.png",
  "Gijon": "/teamlogo/Sporting Gijon.png",
  "Racing DE Ferrol": "/teamlogo/Racing Ferrol.png",
  "SSV Ulm": "/teamlogo/Ulm.png",
  "Preussen Munster": "/teamlogo/SC Preußen Münster.png",
  "R. Oviedo": "/teamlogo/Oviedo.png",
  "Ulm": "/teamlogo/Ulm.png",
  "1. FCK": "/teamlogo/1. FCK.png"
};

export default teamLogos;
